// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wizzccgxqhnlslsqbjjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpenpjY2d4cWhubHNsc3Fiamp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzU4NDcsImV4cCI6MjA3MzYxMTg0N30.DeG5-l-UVTQrj5HNTwDfPc6frMjpa7KnvBcHwGU4FPo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});